name: Build and Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/toss-asst-study:v3 .
          docker push ${{ secrets.DOCKER_USERNAME }}/toss-asst-study:v3

      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | bash

      - name: Login to Railway
        run: |
          echo ${{ secrets.RAILWAY_API_KEY }} > $HOME/.railway/api_token

      - name: Deploy to Railway
        run: |
          railway up --docker --projectId ${{ secrets.RAILWAY_PROJECT_ID }}
