name: Build and Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/toss-asst-study:v3 .
          docker push ${{ secrets.DOCKER_USERNAME }}/toss-asst-study:v3

      - name: Print Railway Project ID (for debugging)
        run: echo "Project ID: ${{ secrets.RAILWAY_PROJECT_ID }}"

      - name: Deploy to Railway using API
        run: |
          curl -X POST https://api.railway.app/v1/projects/${{ secrets.RAILWAY_PROJECT_ID }}/deployments \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"message": "GitHub Actions deploy"}'
